[package]
name = "cybertron-mini-husky-compiler"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
expect-test.workspace = true
indexmap.workspace = true
lazy_static.workspace = true
ordered-float.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
# abstractions
enum-class.workspace = true
shifted-unsigned-int.workspace = true
# cybertron
cybertron.workspace = true
# protocols
husky-text-protocol.workspace = true
# utils
husky-debug-utils.workspace = true
husky-print-utils.workspace = true
husky-rng-utils.workspace = true
husky-wild-utils.workspace = true

[lints]
workspace = true
