[package]
name = "husky-hir-prelude"
version.workspace = true
edition = "2021"

[dependencies]
ordered-float.workspace = true
salsa.workspace = true
# kernel
husky-term-prelude.workspace = true

[dev-dependencies]
husky-hir-prelude = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
