[package]
name = "husky-fly-term"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
smallvec.workspace = true
either.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
idx-arena.workspace = true
vec-like.workspace = true
maybe-result.workspace = true
alt-option.workspace = true
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-regional-token.workspace = true
# kernel
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-coword.workspace = true
husky-expr.workspace = true
husky-scope.workspace = true
husky-place = { path = "../../kernel/husky-place" }
# semantics
husky-dec-signature.workspace = true
# syntax
husky-syn-expr.workspace = true
husky-entity-tree.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# infer
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# lex
husky-toml-token.workspace = true
husky-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-expr.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-decl.workspace = true
husky-fly-term = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
