[package]
name = "husky-io-utils"
version.workspace = true
edition = "2021"

[lib]
doctest = false

[dependencies]
relative-path.workspace = true
thiserror.workspace = true
husky-print-utils.workspace = true
composite-pattern.workspace = true
