[package]
name = "husky-sem-expr"
version.workspace = true
edition = "2021"

[dependencies]
codespan-reporting.workspace = true
either.workspace = true
expect-test.workspace = true
smallvec.workspace = true
thiserror.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
idx-arena.workspace = true
maybe-result.workspace = true
original-error.workspace = true
vec-like.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-term-prelude.workspace = true
husky-dec-signature.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-dec-ty.workspace = true
husky-entity-path.workspace = true
husky-entity-kind.workspace = true
husky-coword.workspace = true
husky-fly-term.workspace = true
husky-expr.workspace = true
husky-place.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-regional-token.workspace = true
# protocol
husky-text-protocol.workspace = true
husky-visual-protocol.workspace = true
# semantics
husky-sem-opr.workspace = true
# syntax
husky-opr.workspace = true
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
husky-syn-opr.workspace = true
# utils
husky-io-utils.workspace = true
husky-print-utils.workspace = true
husky-wild-utils.workspace = true

[dev-dependencies]
# fs
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# kernel
husky-dec-term.workspace = true
# lex
husky-toml-token.workspace = true
husky-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-entity-tree = { workspace = true, features = ["test_helpers"] }
husky-corgi-config-ast.workspace = true
# semantics
husky-sem-expr = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
