[package]
name = "husky-dec-signature"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
smallvec.workspace = true
either.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
vec-like.workspace = true
# fs
husky-vfs = { path = "../../fs/husky-vfs" }
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-regional-token.workspace = true
# syntax
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-opr.workspace = true
# toml
husky-manifest.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# kernel
# infer
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# lex
husky-token.workspace = true
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true

[features]
test_helpers = ["salsa/test_helpers"]
