name = "central-46"
version = "0.1.0"
defaultTargets = ["central-46"]

[[lean_lib]]
name = "Central46"

[[lean_exe]]
name = "central-46"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
