[package]
name = "husky-regional-token"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
# abstractions
enum-class.workspace = true
parsec.workspace = true
salsa.workspace = true
shifted-unsigned-int.workspace = true
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-entity-kind.workspace = true
husky-term-prelude.workspace = true
husky-opr.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
husky-regional-token = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
