import Mathlib
import Visored.Obvious
import Visored.Tactics

set_option maxHeartbeats 20000000000

def h (a b : ℝ) : (((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) ≥ (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) := by
  first
  | have h1 : ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) - (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) ≥ ((0:ℕ) : ℝ) := by calc
    ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) - (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) = ((((((2:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) + (((2:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) - ((((a ^ (2:ℕ) : ℝ) + ((((2:ℕ) : ℝ) * a : ℝ) * b : ℝ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) : ℝ) := by obvious
    _ = ((((a ^ (2:ℕ) : ℝ) - ((((2:ℕ) : ℝ) * a : ℝ) * b : ℝ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) := by obvious
    _ = (((a - b : ℝ) ^ (2:ℕ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) := by obvious
    _ ≥ ((0:ℕ) : ℝ) := by obvious
  | have h2 : (((a - b : ℝ) ^ (2:ℕ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) ≥ ((0:ℕ) : ℝ) := by calc
    (((a - b : ℝ) ^ (2:ℕ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) = ((((a ^ (2:ℕ) : ℝ) - ((((2:ℕ) : ℝ) * a : ℝ) * b : ℝ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) := by obvious
    _ = ((((((2:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) + (((2:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) - ((((a ^ (2:ℕ) : ℝ) + ((((2:ℕ) : ℝ) * a : ℝ) * b : ℝ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((4:ℕ) : ℝ) : ℝ) : ℝ) := by obvious
    _ = ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) - (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by obvious
    _ ≥ ((0:ℕ) : ℝ) := by obvious
  have h3 : ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) - (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) ≥ ((0:ℕ) : ℝ) := by obvious
  have h4 : (((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) ≥ (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) := by
    have d : a = a := by term_derivation_reflection
    have d1 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d2 : (a ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d3 : b = b := by term_derivation_reflection
    have d4 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d5 : (b ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d6 : ((((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_greater comm_ring_add_identity_coercion
    have d7 : ((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d2 d5 eq_identity_coercion eq_identity_coercion d6
    have d8 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d9 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_base_mul_literal
    have d10 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d11 : (((1:ℚ)/2:ℚ) * ((0:ℕ) : ℚ) : ℚ) = (0:ℕ) := by term_derivation_literal_mul_literal
    have d12 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d13 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d14 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d12 d13 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d15 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d16 : b = b := by term_derivation_reflection
    have d17 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d18 : (b ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d19 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d20 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d21 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d19 d20 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d22 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d15 d18 d21 eq_rat_to_real_coercion eq_identity_coercion
    have d23 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d24 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d10 d11 d14 d23 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_rat_real_coercion_triangle rat_real_real_coercion_triangle nat_rat_real_coercion_triangle nat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d25 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d26 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d27 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d25 d26 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d28 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d29 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d9 d24 d27 d28 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_real_real_coercion_triangle rat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d30 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_literal d29
    have d31 : (((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_eq d7 d8 eq_identity_coercion eq_nat_to_real_coercion d30
    have d32 : a = a := by term_derivation_reflection
    have d33 : b = b := by term_derivation_reflection
    have d34 : (a + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_atom_add_product_greater
    have d35 : (a + b : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_atom d34
    have d36 : (a + b : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d32 d33 eq_identity_coercion eq_identity_coercion d35
    have d37 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d38 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_base_mul_literal
    have d39 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d40 : (((1:ℚ)/2:ℚ) * ((0:ℕ) : ℚ) : ℚ) = (0:ℕ) := by term_derivation_literal_mul_literal
    have d41 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d42 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d43 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d41 d42 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d44 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d45 : b = b := by term_derivation_reflection
    have d46 : (b ^ (1:ℕ) : ℝ) = b := by term_derivation_power_one
    have d47 : ((((1:ℚ)/2:ℚ) : ℝ) * b : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d48 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d44 d46 d47 eq_rat_to_real_coercion eq_identity_coercion
    have d49 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d50 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d39 d40 d43 d49 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_rat_real_coercion_triangle rat_real_real_coercion_triangle nat_rat_real_coercion_triangle nat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d51 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d52 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d53 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d51 d52 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d54 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d55 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d38 d50 d53 d54 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_real_real_coercion_triangle rat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d56 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_literal d55
    have d57 : ((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_eq d36 d37 eq_identity_coercion eq_nat_to_real_coercion d56
    have d58 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d59 : (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d60 : (-(((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_neg_product
    have d61 : (-(((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_neg_eq d59 d60
    have d62 : ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_reflection
    have d63 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_reflection
    have d64 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_sum_add_product_greater
    have d65 : ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) + (-(((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d31 d61 eq_identity_coercion eq_identity_coercion d64
    have d66 : ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) - (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_sub_eqs_add_neg d65 neg_identity_coercion
    have d67 : (0:ℕ) = (0:ℕ) := by term_derivation_reflection
    have d68 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d69 : b = b := by term_derivation_reflection
    have d70 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d71 : (b ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d72 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d73 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d74 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d72 d73 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d75 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d68 d71 d74 eq_rat_to_real_coercion eq_identity_coercion
    have d76 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d77 : (-1:ℤ) = (-1:ℤ) := by term_derivation_reflection
    have d78 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d79 : b = b := by term_derivation_reflection
    have d80 : (b ^ (1:ℕ) : ℝ) = b := by term_derivation_power_one
    have d81 : ((((1:ℚ)/2:ℚ) : ℝ) * b : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d82 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d78 d80 d81 eq_rat_to_real_coercion eq_identity_coercion
    have d83 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d84 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d85 : a = a := by term_derivation_reflection
    have d86 : (a ^ (1:ℕ) : ℝ) = a := by term_derivation_power_one
    have d87 : ((((1:ℚ)/2:ℚ) : ℝ) * a : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d88 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d84 d86 d87 eq_rat_to_real_coercion eq_identity_coercion
    have d89 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d90 : ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d83 d88 eq_identity_coercion eq_identity_coercion d89
    have d91 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d92 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d93 : ((-1:ℤ) * ((1:ℕ) : ℤ) : ℤ) = (-1:ℤ) := by term_derivation_mul_one
    have d94 : (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d95 : (((-1:ℤ) : ℝ) * (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d93 d94 eq_int_to_real_coercion comm_ring_mul_int_to_real_coercion comm_ring_mul_identity_coercion
    have d96 : (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d77 d92 d95 eq_int_to_real_coercion eq_identity_coercion
    have d97 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d98 : ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d76 d96 eq_identity_coercion eq_identity_coercion d97
    have d99 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d100 : a = a := by term_derivation_reflection
    have d101 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d102 : (a ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d103 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d104 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d105 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d103 d104 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d106 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d99 d102 d105 eq_rat_to_real_coercion eq_identity_coercion
    have d107 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_reflection
    have d108 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d98 d106 eq_identity_coercion eq_identity_coercion d107
    have d109 : (-((0:ℕ) : ℤ) : ℤ) = (0:ℕ) := by term_derivation_neg_literal
    have d110 : ((((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((0:ℕ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_nf_add_zero
    have d111 : ((((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((-((0:ℕ) : ℤ) : ℤ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d108 d109 eq_identity_coercion eq_int_to_real_coercion d110
    have d112 : ((((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) - ((0:ℕ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_sub_eqs_add_neg d111 neg_nat_to_real_coercion
    have d113 : ((((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) - (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) ≥ ((0:ℕ) : ℝ) ↔ (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) ≥ ((0:ℕ) : ℝ) := by term_derivation_num_comparison
    have d114 : a = a := by term_derivation_reflection
    have d115 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d116 : (a ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d117 : b = b := by term_derivation_reflection
    have d118 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d119 : (b ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d120 : ((((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_greater comm_ring_add_identity_coercion
    have d121 : ((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d116 d119 eq_identity_coercion eq_identity_coercion d120
    have d122 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d123 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_base_mul_literal
    have d124 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d125 : (((1:ℚ)/2:ℚ) * ((0:ℕ) : ℚ) : ℚ) = (0:ℕ) := by term_derivation_literal_mul_literal
    have d126 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d127 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d128 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d126 d127 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d129 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d130 : b = b := by term_derivation_reflection
    have d131 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d132 : (b ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d133 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d134 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d135 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d133 d134 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d136 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d129 d132 d135 eq_rat_to_real_coercion eq_identity_coercion
    have d137 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d138 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d124 d125 d128 d137 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_rat_real_coercion_triangle rat_real_real_coercion_triangle nat_rat_real_coercion_triangle nat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d139 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d140 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d141 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d139 d140 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d142 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d143 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d123 d138 d141 d142 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_real_real_coercion_triangle rat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d144 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_literal d143
    have d145 : (((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_eq d121 d122 eq_identity_coercion eq_nat_to_real_coercion d144
    have d146 : a = a := by term_derivation_reflection
    have d147 : b = b := by term_derivation_reflection
    have d148 : (a + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_atom_add_product_greater
    have d149 : (a + b : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_atom d148
    have d150 : (a + b : ℝ) = ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d146 d147 eq_identity_coercion eq_identity_coercion d149
    have d151 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d152 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_base_mul_literal
    have d153 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * ((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d154 : (((1:ℚ)/2:ℚ) * ((0:ℕ) : ℚ) : ℚ) = (0:ℕ) := by term_derivation_literal_mul_literal
    have d155 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d156 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d157 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d155 d156 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d158 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d159 : b = b := by term_derivation_reflection
    have d160 : (b ^ (1:ℕ) : ℝ) = b := by term_derivation_power_one
    have d161 : ((((1:ℚ)/2:ℚ) : ℝ) * b : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d162 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d158 d160 d161 eq_rat_to_real_coercion eq_identity_coercion
    have d163 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d164 : ((((1:ℚ)/2:ℚ) : ℝ) * (((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d153 d154 d157 d163 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_rat_real_coercion_triangle rat_real_real_coercion_triangle nat_rat_real_coercion_triangle nat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d165 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d166 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d167 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d165 d166 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d168 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d169 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) * (((1:ℚ)/2:ℚ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_literal_mul_sum d152 d164 d167 d168 real_pow_nat_to_real_pow_nat_coercion comm_ring_add_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion eq_identity_coercion comm_ring_mul_identity_coercion rat_real_real_coercion_triangle rat_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle real_real_real_coercion_triangle eq_identity_coercion
    have d170 : (((((0:ℕ) : ℝ) + (((1:ℕ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + (((1:ℕ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_literal d169
    have d171 : ((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_div_eq d150 d151 eq_identity_coercion eq_nat_to_real_coercion d170
    have d172 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d173 : (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d174 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d175 : b = b := by term_derivation_reflection
    have d176 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d177 : (b ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d178 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d179 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d180 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d178 d179 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d181 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d174 d177 d180 eq_rat_to_real_coercion eq_identity_coercion
    have d182 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d183 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d184 : a = a := by term_derivation_reflection
    have d185 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d186 : (a ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d187 : (((1:ℚ)/2:ℚ) * ((1:ℕ) : ℚ) : ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_mul_one
    have d188 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_reflection
    have d189 : ((((1:ℚ)/2:ℚ) : ℝ) * (((1:ℕ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_product d187 d188 eq_rat_to_real_coercion comm_ring_mul_rat_to_real_coercion comm_ring_mul_identity_coercion
    have d190 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d183 d186 d189 eq_rat_to_real_coercion eq_identity_coercion
    have d191 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d192 : ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d182 d190 eq_identity_coercion eq_identity_coercion d191
    have d193 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d194 : b = b := by term_derivation_reflection
    have d195 : (b ^ (1:ℕ) : ℝ) = b := by term_derivation_power_one
    have d196 : ((((1:ℚ)/2:ℚ) : ℝ) * b : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d197 : ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d193 d195 d196 eq_rat_to_real_coercion eq_identity_coercion
    have d198 : (((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_zero_add
    have d199 : ((1:ℚ)/2:ℚ) = ((1:ℚ)/2:ℚ) := by term_derivation_reflection
    have d200 : a = a := by term_derivation_reflection
    have d201 : (a ^ (1:ℕ) : ℝ) = a := by term_derivation_power_one
    have d202 : ((((1:ℚ)/2:ℚ) : ℝ) * a : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_non_one_literal_mul_atom
    have d203 : ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) = ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) := by term_derivation_mul_eq d199 d201 d202 eq_rat_to_real_coercion eq_identity_coercion
    have d204 : (((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_product_add_product_less comm_ring_add_identity_coercion
    have d205 : ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d198 d203 eq_identity_coercion eq_identity_coercion d204
    have d206 : (2:ℕ) = (2:ℕ) := by term_derivation_reflection
    have d207 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) = (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_non_reduced_power
    have d208 : (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) = (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_one_mul
    have d209 : (-(((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_neg_product
    have d210 : (-(((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) := by term_derivation_neg_eq d208 d209
    have d211 : ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = ((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_reflection
    have d212 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_reflection
    have d213 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_sum_add_product_greater
    have d214 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (-(((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_add_eq d192 d210 eq_identity_coercion eq_identity_coercion d213
    have d215 : (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) - (((1:ℕ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) = (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) := by term_derivation_sub_eqs_add_neg d214 neg_identity_coercion
    have d216 : (((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) ≥ (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) ↔ (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + (((-1:ℤ) : ℝ) * (((((0:ℕ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (b ^ (1:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (1:ℕ) : ℝ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) : ℝ) : ℝ) + ((((1:ℚ)/2:ℚ) : ℝ) * (a ^ (2:ℕ) : ℝ) : ℝ) : ℝ) ≥ ((0:ℕ) : ℝ) := by term_derivation_num_comparison
    have d217 : (((a ^ (2:ℕ) : ℝ) + (b ^ (2:ℕ) : ℝ) : ℝ) / ((2:ℕ) : ℝ) : ℝ) ≥ (((a + b : ℝ) / ((2:ℕ) : ℝ) : ℝ) ^ (2:ℕ) : ℝ) := by term_derivation_non_trivial_hypothesis_equivalence h3 d113 d216
    assumption
  obvious
