[package]
name = "cybertron-prototype"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
shifted-unsigned-int.workspace = true
# protocols
husky-text-protocol.workspace = true

[lints]
workspace = true
