[package]
name = "husky-notebook"
version.workspace = true
edition = "2021"

[dependencies]
clap.workspace = true
eframe.workspace = true
egui.workspace = true
egui_dock.workspace = true
tokio.workspace = true
tracing-subscriber = "0.3.16"
# abstractions
ui.workspace = true
enum-index.workspace = true
# devtime
husky-devtime.workspace = true
husky-session.workspace = true
# gui
husky-gui.workspace = true
husky-code-editor.workspace = true
husky-trace-doc = { workspace = true, features = ["egui"] }
# protocols
husky-token-protocol.workspace = true
husky-trace-protocol.workspace = true
husky-standard-trace-protocol = { workspace = true, features = ["egui"] }
# utils
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true
