[package]
name = "husky-completion"
version.workspace = true
edition = "2021"

[dependencies]
lsp-types.workspace = true
husky-text-protocol.workspace = true
husky-ast.workspace = true
husky-syn-expr.workspace = true
husky-print-utils.workspace = true
husky-opr.workspace = true
husky-entity-kind.workspace = true

# infer
[dev-dependencies]
# infer
husky-corgi-config.workspace = true
# lex
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true
