[package]
name = "husky-hir-lazy-expr"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
thiserror.workspace = true
syn = { version = "2.0.0", optional = true }
# abstractions
salsa.workspace = true
enum-class.workspace = true
idx-arena.workspace = true
vec-like.workspace = true
# hir
husky-hir-ty.workspace = true
husky-hir-opr.workspace = true
# kernel
husky-term-prelude.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-coword.workspace = true
husky-eth-term.workspace = true
husky-expr.workspace = true
husky-fly-term.workspace = true
# lex
husky-token.workspace = true
husky-regional-token.workspace = true
husky-text.workspace = true
# semantics
husky-sem-expr.workspace = true
husky-sem-opr = { path = "../../semantics/husky-sem-opr" }
husky-sem-place-contract.workspace = true
# syntax
husky-syn-expr.workspace = true
husky-syn-defn.workspace = true
husky-entity-tree.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
husky-hir-lazy-expr = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
