[package]
name = "visored-lean-transpilation"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
either.workspace = true
rustc-hash.workspace = true
# abstractions
salsa.workspace = true
# latex
latex-prelude = { workspace = true, optional = true }
# lean
lean-opr.workspace = true
lean-hir-expr.workspace = true
lean-item-path.workspace = true
lean-term.workspace = true
# utils
husky-tree-utils = { workspace = true, optional = true }
# visored
visored-annotation = { workspace = true, optional = true }
visored-hir-expr.workspace = true
visored-item-path.workspace = true
visored-opr.workspace = true
visored-zfc-ty.workspace = true

[dev-dependencies]
expect-test.workspace = true
# kernel
husky-coword.workspace = true
# latex
latex-command.workspace = true
latex-environment.workspace = true
latex-ast.workspace = true
# lean
lean-term.workspace = true
lean-sem-expr.workspace = true
# visored
visored-sem-expr.workspace = true
visored-syn-expr.workspace = true
visored-annotation.workspace = true
visored-lean-transpilation = { workspace = true, features = ["test_helpers"] }

[lints]
workspace = true

[features]
test_helpers = [
    "dep:latex-prelude",
    "dep:husky-tree-utils",
    "visored-annotation",
    "visored-hir-expr/test_helpers"
]
