[package]
name = "husky-trace-doc"
version.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
egui = { workspace = true, optional = true }
epaint = { workspace = true, optional = true }
pathdiff.workspace = true
rustc-hash.workspace = true
serde.workspace = true
smallvec.workspace = true
tokio.workspace = true
# abstractions
enum-class.workspace = true
notify-change = { path = "../../abstractions/notify-change" }
ui.workspace = true
# devsoul
# husky-devsoul-interface.workspace = true
# kernel
husky-devsoul.workspace = true
# gui
husky-gui.workspace = true
husky-code-editor.workspace = true
# protocols
husky-value-protocol.workspace = true
husky-visual-protocol.workspace = true
husky-trace-protocol = { workspace = true, features = ["client"] }
# utils
husky-print-utils.workspace = true
# value
husky-value.workspace = true

[dev-dependencies]
tokio.workspace = true
# gui
husky-gui.workspace = true
# protocols
husky-visual-protocol.workspace = true

[features]
egui = ["dep:egui", "dep:epaint"]
