[package]
edition = "2021"
name = "husky-text"
version.workspace = true
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "TODO"

[dependencies]
rustc-hash.workspace = true
lsp-types = { version = "=0.94", features = ["proposed"], optional = true }
serde.workspace = true
# abstraction
ref-index.workspace = true
salsa.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-coword.workspace = true
# protocols
husky-text-protocol.workspace = true
# utils
husky-check-utils.workspace = true
husky-print-utils.workspace = true

[dev-dependencies]
husky-text = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
lsp_support = ["dep:lsp-types", "husky-text-protocol/lsp_support"]
