[package]
name = "husky-minimal-toml-utils"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
# abstractions
salsa.workspace = true
# kernel
husky-coword.workspace = true
# utils
husky-io-utils.workspace = true
husky-print-utils.workspace = true
