[package]
name = "husky-linket"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
fxhash.workspace = true
either.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
is.workspace = true
version-stamp.workspace = true
# fs
husky-manifest.workspace = true
husky-vfs.workspace = true
# hir
husky-hir-eager-expr.workspace = true
husky-hir-lazy-expr.workspace = true
husky-hir-expr.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-item-path-interface.workspace = true
husky-hir-ty.workspace = true
husky-hir-decl.workspace = true
husky-hir-defn.workspace = true
husky-place.workspace = true
# linket
husky-javelin.workspace = true
# protocols
husky-value-protocol.workspace = true
# semantics
husky-sem-expr.workspace = true
husky-sem-item-path-deps.workspace = true
husky-sem-static-mut-deps.workspace = true
husky-sem-var-deps.workspace = true
# syntax
husky-entity-tree.workspace = true
# devsoul
# husky-devsoul-interface.workspace = true
# utils
husky-print-utils.workspace = true
# value
husky-virtual-value.workspace = true

[dev-dependencies]
# hir
husky-hir-ty.workspace = true
husky-hir-decl.workspace = true
husky-hir-prelude.workspace = true
# kernel
husky-eth-signature.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-dec-signature.workspace = true
husky-eth-term.workspace = true
husky-fly-term.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-toml-token.workspace = true
# semantics
husky-corgi-config.workspace = true
husky-sem-expr.workspace = true
husky-sem-place-contract.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-decl.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-expr.workspace = true
husky-syn-defn.workspace = true

[features]
test_helpers = ["salsa/test_helpers"]
