[package]
name = "lean-term"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
# abstractions
enum-class.workspace = true
salsa.workspace = true

[lints]
workspace = true
