[package]
name = "husky-coword"
version.workspace = true
edition = "2021"

[dependencies]
once_cell = "1.16.0"
# abstractions
salsa.workspace = true
vec-like.workspace = true
# utils
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
expect-test.workspace = true
# kernel
husky-coword = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
