[package]
name = "namekian-ast"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
# abstractions
idx-arena.workspace = true
salsa.workspace = true
# protocols
husky-text-protocol.workspace = true

[dev-dependencies]
expect-test.workspace = true

[lints]
workspace = true
