[package]
name = "husky-hir-eager-expr"
version.workspace = true
edition = "2021"

[dependencies]
codespan-reporting.workspace = true
either.workspace = true
expect-test.workspace = true
smallvec.workspace = true
thiserror.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
idx-arena.workspace = true
vec-like.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-term-prelude.workspace = true
husky-entity-path.workspace = true
husky-coword.workspace = true
husky-eth-term.workspace = true
husky-fly-term.workspace = true
husky-expr.workspace = true
husky-place.workspace = true
# hir
husky-hir-ty.workspace = true
husky-hir-opr.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-regional-token.workspace = true
# protocols
husky-text-protocol.workspace = true
# semantics
husky-sem-expr.workspace = true
husky-sem-opr.workspace = true
husky-sem-place-contract.workspace = true
# syntax
husky-entity-tree.workspace = true
# todo: remove this?
husky-syn-expr.workspace = true
husky-syn-defn.workspace = true
# utils
husky-print-utils.workspace = true
husky-decl-macro-utils.workspace = true

[dev-dependencies]
husky-hir-eager-expr = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
