[package]
name = "husky-eth-term"
version.workspace = true
edition = "2021"

[dependencies]
either.workspace = true
once_cell = "1.16.0"
optional = "0.5.0"
thiserror.workspace = true
ordered-float.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
maybe-result.workspace = true
# fs
husky-vfs.workspace = true
# infer
husky-dec-signature.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-scope.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
# syntax
husky-entity-tree.workspace = true
husky-syn-decl.workspace = true
# utils
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# kernel
husky-coword.workspace = true
# infer
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# lex
husky-token.workspace = true
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-expr.workspace = true
husky-corgi-config-ast.workspace = true
husky-eth-term = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
