[package]
name = "latex-ast-hsy-linkets"
edition = "2021"
version = "0.1.0"

[dependencies.ad-hoc-devsoul-dependency]
workspace = true

[dependencies.husky-core]
workspace = true

[dependencies.latex-ast-hsy]
workspace = true

[lib]
plugin = false
proc-macro = false
required-features = []
crate-type = ["cdylib"]
