[package]
name = "visored-term"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
either.workspace = true
num-bigint.workspace = true
lazy_static.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
# abstraction
enum-class.workspace = true
eterned.workspace = true
salsa = { workspace = true, optional = true }
# lisp
lisp-csv.workspace = true
# math
num-helpers.workspace = true
num-traits.workspace = true
# visored
visored-coword.workspace = true
visored-entity-path.workspace = true

[lints]
workspace = true
