[package]
name = "interned"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dashmap.workspace = true
lazy_static.workspace = true
# abstractions
interned-macros.workspace = true

[lints]
workspace = true
