[package]
name = "husky-entity-path"
version.workspace = true
edition = "2021"
description = "husky item path"

[dependencies]
thiserror.workspace = true
url = "2.3.1"
optional = "0.5.0"
once_cell = "1.16.0"
either.workspace = true
rustc_index.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
vec-like.workspace = true
# kernel
husky-vfs.workspace = true
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-item-path-interface.workspace = true

[dev-dependencies]
expect-test.workspace = true
husky-vfs = { workspace = true, features = ["test_helpers"] }
husky-entity-path = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
