[package]
name = "husky-ki"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
# abstractions
salsa.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
# ki
husky-ki-repr-interface.workspace = true
# hir
husky-hir-opr.workspace = true
# linket
husky-linket.workspace = true

[dev-dependencies]
husky-ki = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
