[package]
name = "husky-hir-expr"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
thiserror.workspace = true
syn = { version = "2.0.0", optional = true }
# abstractions
salsa.workspace = true
enum-class.workspace = true
# kernel
husky-entity-path.workspace = true
husky-fly-term.workspace = true
# protocols
husky-entity-kind.workspace = true
# syntax
husky-syn-expr.workspace = true
husky-syn-defn.workspace = true
# semantics
husky-sem-expr.workspace = true
# comptime
husky-hir-eager-expr.workspace = true
husky-hir-lazy-expr.workspace = true

[dev-dependencies]
husky-hir-expr = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
