[package]
name = "husky-manifest"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
semver = "1.0.17"
# abstractions
salsa.workspace = true
vec-like.workspace = true
# lex
husky-text-protocol.workspace = true
husky-toml-token.workspace = true
# infer
husky-corgi-config.workspace = true
# kernel
husky-coword.workspace = true
# fs
husky-vfs.workspace = true
# toml
husky-toml-ast.workspace = true
husky-corgi-config-ast.workspace = true
husky-manifest-ast.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
husky-manifest = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers", "husky-vfs/test_helpers"]
