[package]
name = "husky-devtime"
version.workspace = true
edition = "2021"

[dependencies]
dashmap.workspace = true
either.workspace = true
salsa.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
# abstractions
vec-like.workspace = true
serde-impl = { workspace = true, features = ["json"] }
# serde-impl = { path = "../../abstractions/serde-impl", features = ["json"] }
# comptime
husky-dev-comptime.workspace = true
# devsoul
husky-devsoul.workspace = true
# devtime
husky-trace.workspace = true
# fs
husky-vfs.workspace = true
# hir
husky-hir-eager-expr.workspace = true
# kernel
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-coword.workspace = true
husky-opr.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-item-path-interface.workspace = true
# ki
husky-ki-repr-interface.workspace = true
# lex
# linket
husky-linket.workspace = true
husky-linket-impl.workspace = true
husky-standard-linket-impl.workspace = true
# protocols
husky-figure-zone-protocol.workspace = true
husky-text-protocol.workspace = true
husky-trace-protocol = { workspace = true, features = ["server"] }
husky-value-protocol.workspace = true
husky-visual-protocol.workspace = true
# runtime
husky-dev-runtime = { path = "../../runtime/husky-dev-runtime" }
husky-ki-repr.workspace = true
# syntax
husky-ast.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
# utils
husky-check-utils.workspace = true
husky-print-utils.workspace = true
husky-sync-utils.workspace = true
husky-wild-utils.workspace = true
# value
husky-value.workspace = true
# vm
husky-vm.workspace = true
# vmir
husky-vmir.workspace = true

[dev-dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-test.workspace = true
# protocols
husky-trace-protocol = { workspace = true, features = ["test_helpers"] }
husky-standard-trace-protocol.workspace = true
# devsoul
husky-standard-devsoul.workspace = true
# utils
husky-path-utils.workspace = true
