[package]
name = "husky-path-utils"
version.workspace = true
edition = "2021"

[lib]
doctest = false

[dependencies]
thiserror.workspace = true
relative-path = "1.7.2"
pathdiff = "0.2.1"
# abstractions
salsa.workspace = true
# kernel
husky-coword.workspace = true
# utils
husky-print-utils.workspace = true
husky-check-utils.workspace = true
husky-minimal-toml-utils = { path = "../../utils/husky-minimal-toml-utils" }

[dev-dependencies]
expect-test.workspace = true
# utils
husky-path-utils = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
