[package]
name = "husky-corgi-config-ast"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
# lex
husky-text-protocol.workspace = true
husky-toml-token.workspace = true
# kernel
husky-coword.workspace = true
# fs
husky-vfs.workspace = true
# syntax
husky-toml-ast.workspace = true

[dev-dependencies]
husky-vfs = { workspace = true, features = ["test_helpers"] }
husky-corgi-config-ast = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
