[package]
name = "husky-dev-runtime"
version.workspace = true
edition = "2021"

[dependencies]
serde.workspace = true
salsa.workspace = true
lsp-types.workspace = true
smallvec.workspace = true
relative-path = "1.7.2"
# abstractions
idx-arena.workspace = true
vec-like.workspace = true
# comptime
husky-dev-comptime.workspace = true
# fs
husky-vfs.workspace = true
# hir
husky-hir-opr.workspace = true
husky-hir-lazy-expr.workspace = true
# kernel
husky-coword.workspace = true
husky-dec-signature.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
husky-item-path-interface.workspace = true
husky-term-prelude.workspace = true
husky-opr.workspace = true
# ki
husky-ki.workspace = true
husky-ki-repr.workspace = true
husky-ki-repr-interface.workspace = true
# lex
husky-text-protocol.workspace = true
husky-token.workspace = true
# linket
husky-linket.workspace = true
husky-linket-impl.workspace = true
# protocols
husky-figure-zone-protocol.workspace = true
husky-trace-protocol = { workspace = true, features = ["test_helpers"] }
husky-visual-protocol.workspace = true
# syntax
husky-entity-tree.workspace = true
husky-ast.workspace = true
# devsoul
# husky-devsoul-interface.workspace = true
husky-devsoul.workspace = true
# husky-standard-devsoul-interface.workspace = true
husky-standard-devsoul.workspace = true
# utils
husky-check-utils.workspace = true
husky-path-utils.workspace = true
husky-print-utils.workspace = true
husky-sync-utils.workspace = true
husky-wild-utils.workspace = true
# vm
husky-vm.workspace = true
husky-vmir.workspace = true
# value
husky-value.workspace = true

[dev-dependencies]
husky-ast = { workspace = true, features = ["test_helpers"] }
# ad hoc
# linket
husky-standard-linket-impl.workspace = true
# linktime
husky-mono-linktime.workspace = true
# protocols
husky-standard-trace-protocol.workspace = true
