[package]
name = "husky-hir-decl"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
thiserror.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
# hir
husky-hir-ty.workspace = true
husky-hir-eager-expr.workspace = true
husky-hir-lazy-expr.workspace = true
husky-hir-expr.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-coword.workspace = true
husky-eth-term.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
husky-term-prelude.workspace = true
# semantics
husky-sem-expr.workspace = true
# syntax
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# abstractions
salsa = { path = "../../abstractions/salsa", features = ["test_helpers"] }
# hir
husky-hir-prelude.workspace = true
# kernel
# infer
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-toml-token.workspace = true
# kernel
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-dec-signature.workspace = true
husky-place.workspace = true
# semantics
husky-sem-place-contract.workspace = true
husky-sem-item-path-deps.workspace = true
husky-sem-static-mut-deps.workspace = true
husky-sem-var-deps.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-decl.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-expr.workspace = true
husky-syn-defn.workspace = true

[features]
test_helpers = ["salsa/test_helpers"]
