[package]
name = "husky-hover"
version.workspace = true
edition = "2021"

[dependencies]
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
# abstractions
salsa.workspace = true
# fs
husky-vfs.workspace = true
# ide
husky-documentation = { path = "../../ide/husky-documentation" }
# infer
husky-token-info.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-text-protocol.workspace = true
husky-regional-token.workspace = true
# kernel
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
# semantics
husky-sem-place-contract.workspace = true
husky-sem-expr.workspace = true
# syntax
husky-ast.workspace = true
husky-syn-expr.workspace = true
husky-entity-tree.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
husky-place.workspace = true
# lex
husky-text = { path = "../../lex/husky-text", features = ["lsp_support"] }
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
husky-corgi-config-ast.workspace = true
# infer
husky-manifest.workspace = true
husky-dec-signature.workspace = true
husky-corgi-config.workspace = true
husky-hover = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
