[package]
name = "husky-text-protocol"
version.workspace = true
edition = "2021"

[dependencies]
serde.workspace = true
lsp-types = { workspace = true, optional = true }
rustc-hash.workspace = true
# abstractions
shifted-unsigned-int.workspace = true

[features]
lsp_support = ["dep:lsp-types"]
