[package]
name = "husky-syn-decl"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
derive-getters = "0.2.0"
either.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
vec-like.workspace = true
original-error.workspace = true
parsec.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-entity-path.workspace = true
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-opr.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-regional-token.workspace = true
# syntax
husky-syn-expr.workspace = true
husky-entity-tree.workspace = true
husky-crate-decl-ast.workspace = true
husky-item-decl-ast.workspace = true
# utils
husky-print-utils.workspace = true
husky-iter-utils.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# kernel
husky-term-prelude.workspace = true
# lex
husky-toml-token.workspace = true
husky-token = { path = "../../lex/husky-token", features = ["test_helpers"] }
# semantics
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-decl = { workspace = true, features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
