[package]
name = "husky-toml-token"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
# abstractions
salsa.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text-protocol.workspace = true
# kernel
husky-coword.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
salsa.workspace = true

[features]
test_helpers = ["salsa/test_helpers", "husky-vfs/test_helpers"]
