[package]
name = "husky-syn-expr"
version.workspace = true
edition = "2021"

[dependencies]
codespan-reporting.workspace = true
ordered-float.workspace = true
optional = "0.5.0"
thiserror.workspace = true
smallvec.workspace = true
either.workspace = true
# abstractions
parsec.workspace = true
salsa.workspace = true
idx-arena.workspace = true
vec-like.workspace = true
original-error.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text.workspace = true
# TODO: previously commented: `husky-token` shouldn't be included for dependencies!!
# think about it
husky-token.workspace = true
husky-token-data.workspace = true
husky-regional-token.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-entity-kind.workspace = true
husky-term-prelude.workspace = true
husky-opr.workspace = true
husky-expr = { path = "../../kernel/husky-expr" }
# protocols
husky-text-protocol.workspace = true
# syntax
husky-entity-tree.workspace = true
husky-item-decl-ast.workspace = true
husky-item-defn-ast.workspace = true
husky-syn-opr.workspace = true
# utils
husky-print-utils.workspace = true
husky-check-utils.workspace = true
husky-expect-test-snippets-utils = { path = "../../utils/husky-expect-test-snippets-utils" }

[dev-dependencies]
expect-test.workspace = true
# abstractions
salsa = { path = "../../abstractions/salsa", features = ["test_helpers"] }
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# infer
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# kernel
husky-coword.workspace = true
# lex
husky-text.workspace = true
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true

[features]
test_helpers = ["salsa/test_helpers"]
