[workspace]
members = ["latex-ast-hsy-linkets"]
resolver = "2"

[workspace.dependencies.ad-hoc-devsoul-dependency]
path = "../../ad-hoc-devsoul-dependency"

[workspace.dependencies.husky-core]
path = "../../../library/core"

[workspace.dependencies.latex-ast-hsy]
path = ".."

[workspace.dependencies.latex-ast-hsy-linkets]
path = "latex-ast-hsy-linkets"
