[package]
name = "cybertron-mini-lean-compiler"
version.workspace = true
description = "example mini-lean-compiler in cybertron"
license = "MIT OR Apache-2.0"

[dependencies]
cybertron-mini-lean-tokens = "0.1.0"
